using System.Windows;

namespace sample;

/// <summary>
/// WXSG C# Expressions Demo
///
/// Because WpfXsgEnabled=true in sample.csproj, InitializeComponent and all
/// x:Name field declarations are generated by the WXSG source generator.
///
/// All {cs: ...} expressions in the XAML are compiled directly into
/// InitializeComponent() as C# statements — no IValueConverter, no reflection.
/// </summary>
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
    }
}
