using System.Windows;

namespace sample;

/// <summary>
/// WXSG x:Code Demo
///
/// The InitializeComponent() method, x:Name field declarations, and event handlers
/// (OnButtonClick, OnClearClick) are all generated by the WXSG source generator
/// based on the XAML definition, including the <x:Code> block.
///
/// This demonstrates that C# code can be embedded directly in XAML without needing
/// a traditional code-behind file (this file exists only for design-time support).
/// </summary>
public partial class MainWindowXCode : Window
{
    public MainWindowXCode()
    {
        InitializeComponent();
    }
}
