using System.Windows;

namespace sample;

/// <summary>
/// WXSG demo — code-behind for MainWindow.
///
/// Because WpfXsgEnabled=true in sample.csproj, the partial class members
/// (InitializeComponent, _contentLoaded, IComponentConnector.Connect, and all
/// x:Name field declarations) are generated by the WXSG source generator rather
/// than by WPF's MSBuild MarkupCompilePass1 task.
///
/// Inspect the generated file in:
///   obj/Debug/net6.0-windows/sample_MainWindow.wpf.g.cs
///
/// The typed fields (e.g. GreetingLabel, FirstNameBox, ItemsList) are accessible
/// here without any casting — WXSG resolved their types via
/// System.Windows.Markup.XmlnsDefinitionAttribute at code-generation time.
/// </summary>
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
    }

    private void AddButton_Click(object sender, RoutedEventArgs e)
    {
        if (DataContext is GreetingViewModel vm)
            vm.AddItem();

        // Typed access to x:Name fields — no FindName() cast needed.
        NewItemBox.Focus();
    }
}
