using System.Text;
using XamlToCSharpGenerator.Core.Abstractions;
using XamlToCSharpGenerator.Core.Models;

namespace XamlToCSharpGenerator.WPF.Emission;

/// <summary>
/// Phase 1 code emitter for WPF XAML.
///
/// Generates a <c>partial class</c> that replaces WPF's MSBuild-generated <c>.g.cs</c> file:
/// <list type="bullet">
///   <item>Typed field declarations for all <c>x:Name</c> elements</item>
///   <item><c>InitializeComponent()</c> that calls <c>Application.LoadComponent</c>
///         and then wires named fields via <c>FindName</c></item>
///   <item>A no-op <c>IComponentConnector.Connect()</c> (BAML calls it during load;
///         field wiring is deferred to <c>FindName</c> after load completes)</item>
/// </list>
///
/// Phase 3 (future): replace <c>LoadComponent</c> with full object-graph construction
/// so that BAML is no longer needed at runtime.
/// </summary>
public sealed class WpfCodeEmitter : IXamlCodeEmitter
{
    private const string GeneratorVersion = "0.1.0";
    private const string GeneratorName = "XamlToCSharpGenerator.Generator.WPF";

    public (string HintName, string Source) Emit(ResolvedViewModel viewModel)
    {
        var doc = viewModel.Document;
        if (doc.ClassFullName is null)
            return (string.Empty, string.Empty);

        var source = BuildSource(viewModel, doc);
        var hintName = $"{doc.ClassFullName.Replace('.', '_').Replace('+', '_')}.wpf.g.cs";
        return (hintName, source);
    }

    private static string BuildSource(ResolvedViewModel viewModel, XamlDocumentModel doc)
    {
        var sb = new StringBuilder(512);
        var ns = doc.ClassNamespace;
        var className = doc.ClassName;
        var modifier = viewModel.ClassModifier;
        var hasNs = !string.IsNullOrEmpty(ns);

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Generated by {GeneratorName} {GeneratorVersion}");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("#pragma warning disable CS0169, CS8618");
        sb.AppendLine();

        if (hasNs)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        var indent = hasNs ? "    " : string.Empty;

        // Partial class declaration — implements IComponentConnector for BAML load callback.
        sb.AppendLine($"{indent}{modifier} partial class {className} : global::System.Windows.Markup.IComponentConnector");
        sb.AppendLine($"{indent}{{");

        var memberIndent = indent + "    ";

        // Named element fields
        foreach (var element in viewModel.NamedElements)
        {
            sb.AppendLine($"{memberIndent}#line {element.Line}");
            sb.AppendLine($"{memberIndent}[global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Microsoft.Performance\", \"CA1823:AvoidUnusedPrivateFields\")]");
            sb.AppendLine($"{memberIndent}{element.FieldModifier} global::{element.TypeName} {element.Name};");
            sb.AppendLine($"{memberIndent}#line default");
            sb.AppendLine();
        }

        // _contentLoaded guard
        sb.AppendLine($"{memberIndent}private bool _contentLoaded;");
        sb.AppendLine();

        // InitializeComponent
        EmitInitializeComponent(sb, memberIndent, viewModel);
        sb.AppendLine();

        // IComponentConnector.Connect — no-op; field wiring is done via FindName above.
        EmitConnect(sb, memberIndent);

        sb.AppendLine($"{indent}}}");

        if (hasNs)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitInitializeComponent(
        StringBuilder sb,
        string indent,
        ResolvedViewModel viewModel)
    {
        sb.AppendLine($"{indent}[global::System.Diagnostics.DebuggerNonUserCode]");
        sb.AppendLine($"{indent}[global::System.CodeDom.Compiler.GeneratedCode(\"{GeneratorName}\", \"{GeneratorVersion}\")]");
        sb.AppendLine($"{indent}public void InitializeComponent()");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    if (_contentLoaded) return;");
        sb.AppendLine($"{indent}    _contentLoaded = true;");
        sb.AppendLine();

        // Phase 1: still delegates to BAML loading via LoadComponent.
        // Phase 3 will replace this with direct object construction.
        var relUri = EscapeStringLiteral(viewModel.BuildUri);
        sb.AppendLine($"{indent}    // Phase 1: load from BAML resource. Phase 3 will replace with pure C# construction.");
        sb.AppendLine($"{indent}    var resourceLocater = new global::System.Uri(\"{relUri}\", global::System.UriKind.Relative);");
        sb.AppendLine($"{indent}    global::System.Windows.Application.LoadComponent(this, resourceLocater);");

        // Wire up named fields after BAML loading has populated the name scope.
        if (!viewModel.NamedElements.IsEmpty)
        {
            sb.AppendLine();
            foreach (var element in viewModel.NamedElements)
                sb.AppendLine($"{indent}    this.{element.Name} = (global::{element.TypeName})this.FindName(\"{element.Name}\");");
        }

        sb.AppendLine($"{indent}}}");
    }

    private static void EmitConnect(StringBuilder sb, string indent)
    {
        sb.AppendLine($"{indent}[global::System.Diagnostics.DebuggerNonUserCode]");
        sb.AppendLine($"{indent}[global::System.CodeDom.Compiler.GeneratedCode(\"{GeneratorName}\", \"{GeneratorVersion}\")]");
        sb.AppendLine($"{indent}[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"{indent}void global::System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    // Field wiring is performed via FindName inside InitializeComponent.");
        sb.AppendLine($"{indent}    _contentLoaded = true;");
        sb.AppendLine($"{indent}}}");
    }

    private static string EscapeStringLiteral(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
