<#
.SYNOPSIS
    Builds the XamlDesigner tool from the WpfDesigner submodule.

.DESCRIPTION
    Compiles external/WpfDesigner/XamlDesigner/Demo.XamlDesigner.csproj and
    places the output in tools/XamlDesigner/.

    To override the TargetFramework for all projects in the submodule without
    modifying any source file, the script temporarily writes a
    Directory.Build.props in external/WpfDesigner/ and removes it when done.
    MSBuild searches for Directory.Build.props upward from each project file,
    so every project in the submodule inherits the override consistently during
    both restore and build.

.PARAMETER Configuration
    MSBuild configuration to use (default: Release).

.PARAMETER TargetFramework
    Target framework to compile for.  Leave empty to auto-detect the highest
    .NET SDK installed on this machine (recommended).
    Override only when pinning to a specific version, e.g. net10.0-windows.

.EXAMPLE
    .\scripts\build-designer.ps1
    .\scripts\build-designer.ps1 -TargetFramework net10.0-windows
    .\scripts\build-designer.ps1 -Configuration Debug
#>
param(
    [string]$Configuration   = "Release",
    [string]$TargetFramework = ""
)

$ErrorActionPreference = "Stop"

$RepoRoot        = Split-Path -Parent $PSScriptRoot
$SubmoduleCsproj = Join-Path $RepoRoot "external\WpfDesigner\XamlDesigner\Demo.XamlDesigner.csproj"
$SubmoduleRoot   = Join-Path $RepoRoot "external\WpfDesigner"
$OutputDir       = Join-Path $RepoRoot "tools\XamlDesigner"
$TfmFile         = Join-Path $OutputDir "designer.tfm"
$TempProps       = Join-Path $SubmoduleRoot "Directory.Build.props"

# Verify submodule is initialised
if (-not (Test-Path $SubmoduleCsproj)) {
    Write-Error @"
WpfDesigner submodule not found at:
  $SubmoduleCsproj

Initialise it first:
  git submodule update --init --recursive
"@
    exit 1
}

# Ensure dotnet CLI is available
if (-not (Get-Command dotnet -ErrorAction SilentlyContinue)) {
    Write-Error "dotnet CLI not found on PATH.  Install the .NET SDK from https://dot.net"
    exit 1
}

# Auto-detect highest installed .NET SDK when TargetFramework not specified
if (-not $TargetFramework) {
    $sdkList = & dotnet --list-sdks 2>$null
    $highest = $sdkList |
        ForEach-Object { if ($_ -match '^(\d+)\.\d+\.\d+') { [int]$Matches[1] } } |
        Where-Object { $_ -ge 5 } |
        Sort-Object -Descending |
        Select-Object -First 1
    $TargetFramework = if ($highest) { "net${highest}.0-windows" } else { "net10.0-windows" }
    Write-Host "  TargetFramework : $TargetFramework (auto-detected)" -ForegroundColor DarkGray
} else {
    Write-Host "  TargetFramework : $TargetFramework (explicit)" -ForegroundColor DarkGray
}

Write-Host ""
Write-Host "=== WPF Designer Tools Build ===" -ForegroundColor Cyan
Write-Host "  Project       : $SubmoduleCsproj"
Write-Host "  Output        : $OutputDir"
Write-Host "  Configuration : $Configuration"
Write-Host "  Framework     : $TargetFramework"
Write-Host ""

# Create output directory if needed
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir | Out-Null
}

# Write a temporary Directory.Build.props so every project in the submodule
# inherits the same TargetFramework during restore AND build — no csproj edits needed.
$propsContent = @"
<!-- Auto-generated by build-designer.ps1 — do not commit -->
<Project>
  <PropertyGroup>
    <TargetFramework>$TargetFramework</TargetFramework>
  </PropertyGroup>
</Project>
"@
Set-Content -Path $TempProps -Value $propsContent -Encoding UTF8
Write-Host "  Wrote temporary Directory.Build.props ($TargetFramework)" -ForegroundColor DarkGray

try {
    Write-Host ""
    Write-Host "Running: dotnet restore ..." -ForegroundColor Yellow
    & dotnet restore "$SubmoduleCsproj" --nologo
    if ($LASTEXITCODE -ne 0) { Write-Error "Restore failed with exit code $LASTEXITCODE."; exit $LASTEXITCODE }

    Write-Host "Running: dotnet build ..." -ForegroundColor Yellow
    & dotnet build "$SubmoduleCsproj" `
        --configuration $Configuration `
        --output "$OutputDir" `
        --nologo `
        --no-restore
    if ($LASTEXITCODE -ne 0) { Write-Error "Build failed with exit code $LASTEXITCODE."; exit $LASTEXITCODE }
}
finally {
    # Always clean up the temporary file
    Remove-Item $TempProps -ErrorAction SilentlyContinue
    Write-Host "  Removed temporary Directory.Build.props" -ForegroundColor DarkGray
}

# Record the TFM so the extension can check compatibility at launch time
Set-Content -Path $TfmFile -Value $TargetFramework -Encoding UTF8

# Report result
$exe = Join-Path $OutputDir "XamlDesigner.exe"
$dll = Join-Path $OutputDir "Demo.XamlDesigner.dll"
Write-Host ""
if (Test-Path $exe) {
    Write-Host "Build succeeded." -ForegroundColor Green
    Write-Host "  Executable : $exe"
} elseif (Test-Path $dll) {
    Write-Host "Build succeeded." -ForegroundColor Green
    Write-Host "  Assembly   : $dll"
} else {
    Write-Warning "Build completed but expected outputs were not found in $OutputDir."
}
